apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-config
  namespace: payment-gateway
data:
  DATABASE_URL: "postgres://postgres:postgres@pgbouncer.payment-gateway.svc.cluster.local:5432/example_sqlx_payment_gateway"
  PORT: "5000"
  JWT_SECRET: "hesoyam"
  RUN_MIGRATIONS: "false"
  RUST_BACKTRACE: "1"
  DB_MAX_CONNECTION: "30"
  DB_MIN_CONNECTION: "10"
  DEV_MODE: "false"
  ENABLE_FILE_LOG: "false"
  AUTH_GRPC_PORT: "50051"
  AUTH_METRIC_PORT: "8081"
  CARD_GRPC_PORT: "50052"
  CARD_METRIC_PORT: "8082"
  MERCHANT_GRPC_PORT: "50053"
  MERCHANT_METRIC_PORT: "8083"
  ROLE_GRPC_PORT: "50054"
  ROLE_METRIC_PORT: "8084"
  SALDO_GRPC_PORT: "50055"
  SALDO_METRIC_PORT: "8085"
  TOPUP_GRPC_PORT: "50056"
  TOPUP_METRIC_PORT: "8086"
  TRANSACTION_GRPC_PORT: "50057"
  TRANSACTION_METRIC_PORT: "8087"
  TRANSFER_GRPC_PORT: "50058"
  TRANSFER_METRIC_PORT: "8088"
  USER_GRPC_PORT: "50059"
  USER_METRIC_PORT: "8089"
  WITHDRAW_GRPC_PORT: "50060"
  WITHDRAW_METRIC_PORT: "8090"
  AUTH_GRPC_ADDR: "http://auth.payment-gateway.svc.cluster.local:50051"
  CARD_GRPC_ADDR: "http://card.payment-gateway.svc.cluster.local:50052"
  MERCHANT_GRPC_ADDR: "http://merchant.payment-gateway.svc.cluster.local:50053"
  ROLE_GRPC_ADDR: "http://role.payment-gateway.svc.cluster.local:50054"
  SALDO_GRPC_ADDR: "http://saldo.payment-gateway.svc.cluster.local:50055"
  TOPUP_GRPC_ADDR: "http://topup.payment-gateway.svc.cluster.local:50056"
  TRANSACTION_GRPC_ADDR: "http://transaction.payment-gateway.svc.cluster.local:50057"
  TRANSFER_GRPC_ADDR: "http://transfer.payment-gateway.svc.cluster.local:50058"
  USER_GRPC_ADDR: "http://user.payment-gateway.svc.cluster.local:50059"
  WITHDRAW_GRPC_ADDR: "http://withdraw.payment-gateway.svc.cluster.local:50060"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.payment-gateway.svc.cluster.local:4317"