apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: payment-gateway
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: [ "alertmanager.payment-gateway.svc.cluster.local:9093" ]

    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: [ 'otel-collector.payment-gateway.svc.cluster.local:8889' ]
            labels:
              application: 'Otel Collector'
              environment: 'production'

      - job_name: "node-exporter"
        scrape_interval: 5s
        static_configs:
          - targets: [ "node-exporter.payment-gateway.svc.cluster.local:9100" ]
            labels:
              application: "node-exporter"