apiVersion: apps/v1
kind: Deployment
metadata:
  name: role
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: role
  template:
    metadata:
      labels:
        app: role
    spec:
      containers:
      - name: role
        image: payment-gateway-sqlx/role:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-env-config
        ports:
        - containerPort: 50054
        volumeMounts:
        - name: logs
          mountPath: /var/log/app
      volumes:
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: role
  namespace: payment-gateway
spec:
  selector:
    app: role
  ports:
  - name: grpc
    port: 50054
    targetPort: 50054
  - name: metrics
    port: 8084
    targetPort: 8084
  type: ClusterIP