apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
      - name: transfer
        image: payment-gateway-sqlx/transfer:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-env-config
        ports:
        - containerPort: 50058
        volumeMounts:
        - name: logs
          mountPath: /var/log/app
      volumes:
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: transfer
  namespace: payment-gateway
spec:
  selector:
    app: transfer
  ports:
  - name: grpc
    port: 50058
    targetPort: 50058
  - name: metrics
    port: 8088
    targetPort: 8088
  type: ClusterIP