name: Build and push Rust binaries
on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    paths:
      - 'backend/Dockerfile.*'
      - 'backend/src/**'
      - 'backend/Cargo.*'

env:
  GHCR_REGISTRY: ghcr.io
  REPO_NAME: mamangrust/example-payment-gateway-sqlx
  SQLX_OFFLINE: true

defaults:
  run:
    working-directory: backend

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: auth
            dockerfile: Dockerfile.auth
          - name: user
            dockerfile: Dockerfile.user
          - name: card
            dockerfile: Dockerfile.card
          - name: merchant
            dockerfile: Dockerfile.merchant
          - name: role
            dockerfile: Dockerfile.role
          - name: saldo
            dockerfile: Dockerfile.saldo
          - name: transaction
            dockerfile: Dockerfile.transaction
          - name: topup
            dockerfile: Dockerfile.topup
          - name: transfer
            dockerfile: Dockerfile.transfer
          - name: withdraw
            dockerfile: Dockerfile.withdraw
          - name: apigateway
            dockerfile: Dockerfile.apigateway
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
      
      - name: Run rustfmt
        run: cargo fmt --all -- --check
        env:
          SQLX_OFFLINE: true
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          SQLX_OFFLINE: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.target.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=${{ matrix.target.name }}
            org.opencontainers.image.description=Rust binary image for ${{ matrix.target.name }} service
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/${{ matrix.target.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.GHCR_REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.target.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SQLX_OFFLINE=true